// x.unshift(0)
// x.unshift(5)
// console.log(x)
// x.shift()
// console.log(x)

// console.log(x.__proto__)
// x.push(3)
// console.log(x)
// x.push(5)
// console.log(x)
// x.pop()
// console.log(x)
// console.log(x.toString())
// console.log(x.toSorted())
// console.log(x.toReversed())
// console.log(x.values())

// x.sort()
// console.log(x.at(2))
// console.log(x.includes(2))
// console.log(x.includes(56))
// console.log(x.indexOf(-55))

let x = new Array(1, 2, -5, -110, 45, 69)
console.log(x)
let y = x.slice(1, 3)
console.log(y)
console.log(x)